version: 2.1

workflows:
  test-app:
    jobs:
      - test:
          context: env

jobs:
  test:
    docker:
      - image: sagonzalezn/vagrant-node:v1.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: node --version
