version: 2.1

on:
  push:
    branches:
      - main
      - feature/Demo
    pull_request:
      - main


workflows:
  build_test:
    jobs:
      - build_and_test:
          context: env #contexto para variables de entorno
  schedule:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build_and_test
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main

jobs:
  build_and_test:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: cd app && yarn install
      - run:
          name: Run tests
          command: cd app &&  yarn test
      - run:
          name: Run Confirmation Message
          command: echo "All tests passed :D"
  
  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:F09I/es6VVTMxbQW01Ifa4vkYlk5EOd56pjzrosmuh8"
      - run:
          name: Deploy Containers to Vagrant Machine
          command: |
            apt update
            apt install openssh-client -y
            apt install net-tools
            ifconfig
            ssh -o StrictHostKeyChecking=no vagrant@$SSH_CONNECTION '
              docker compose -f /vagrant/docker-compose.yml pull

              docker compose -f /vagrant/docker-compose.yml up -d --build
            '

  
