version: 2.1

workflows:
  build_test_deploy:
    jobs:
      - build_and_test:
          context: env #contexto para variables de entorno
  schedule:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: sagonzalezn/vagrant-node:v1.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: cd app && yarn install
      - run:
          name: Run tests
          command: cd app &&  yarn test
      - run:
          name: Run Commit Command
          command: echo "commiting changes"
  
